### ISSUE TITLE
Needs standardized README

### ISSUE THREAD

**Issue by RichardLitt** [ipld/js-ipld-eth-block#1]
Also, license.

**Comment by kumavis** [comment]
@RichardLitt is there a template for the standard?

**Comment by RichardLitt** [comment]
There isn't quite a template. There is a spec at github.com/RichardLitt/standard-readme, and a generator linked there. But there should be a standard template, you're right, for IPLD repositories. I just standardized the ipld/ipld repo -- see ipld/ipld#1. This is how repos should look. Upon that being merged, I can make a template. Don't worry about this for now -- assigning this to me.

**Comment by kumavis** [comment]
@RichardLitt just a reminder ^

**Comment by RichardLitt** [comment]
@kumavis Created template, opened PR. Take a look. Thanks for the reminder. :)
