### ISSUE TITLE
use in ethereumjs-block

### ISSUE THREAD

**Issue by wanderer** [ipld/js-ipld-eth-block#4]
Would it make sense to have this as a method on ethereumjs-block? it could exports `toIPLD` and `fromIPLD`

**Comment by kumavis** [comment]
good question! it would mean pulling in more deps for `eth-block`. we should keep `eth-block` simple. I think they are fine separate for now.

**Comment by wanderer** [comment]
ok sounds good. So when I pull a ethereum-block from the DAG service, will I get a etheruemjs-block or just the raw buffer?

**Comment by wanderer** [comment]
So really what you want here is just to parse the block. So maybe we should make just a standalone block parser that js-ipld-eth-block and ethereumjs-block uses. B/c as it stands now js-ipld-eth-block use ethereumjs-block to do parsing. But ethereumks-block all has all the logic to do validation (which is quite alot).

**Comment by kumavis** [comment]
No, we don't need the validation. Maybe we can move to something more minimal. Right now `ethereumjs-block` is pulling in `ethereumjs-util` which brings in all our crypto.

In the case of the tx, we need the crypto to pull out the `from` address from the signature, so its slightly more involved than just parsing.
